schema_version = "1.0.0"

id = "render_setup_tool"
version = "1.0.1"
name = "Render Setup Tool"
tagline = "One button solution for setting your render settings"
maintainer = "Andreas Wetter <andreas.wetter@sejfo.se>"
type = "add-on"

blender_version_min = "4.2.0"

license = [
    "SPDX:GPL-3.0-or-later"
]