schema_version = "1.0.0"

id = "sejfo_tool_suite"
version = "1.1.0"
name = "Sejfo Tool Suite"
tagline = "Clean up and optimize CAD assemblies and Visual Components simulations"
maintainer = "Andreas Wetter <andreas.wetter@sejfo.se>"
type = "add-on"

blender_version_min = "4.2.0"

license = [
    "SPDX:GPL-3.0-or-later",
]
